### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by ghost** [openela/kernel-lts#1]
This commit: https://github.com/openela/kernel-lts/commit/49d8396c56ccab57ecb82eac5f03d2ddbc6c5d5f gives me this error:

```
../fs/ext4/ioctl.c:541:7: error: incompatible pointer to integer conversion assigning to 'int' from 'struct super_block *' [-Wint-conversion]
  541 |                 ret = freeze_bdev(sb->s_bdev);
      |                     ^ ~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[3]: *** [../scripts/Makefile.build:364: fs/ext4/ioctl.o] Error 1
make[2]: *** [../scripts/Makefile.build:678: fs/ext4] Error 2
make[2]: *** Waiting for unfinished jobs....
```

I think this function isn't the same as "bdev_freeze" which return an integer. Should I skip this commit ?

**Comment by ghost** [comment]
Fixed with this commit 🥰
https://github.com/chiteroman/kernel_vayu/commit/1885eeb1e704f5875df8e668839b5dca414c50df

**Comment by harshimogalapalli** [comment]
Thanks for reporting this issue, we will fix this in the next release.
