### ISSUE TITLE
versioning naming propose

### ISSUE THREAD

**Issue by jututt** [openela/kernel-lts#12]
Could next version naming be 4.19.xxx+100
i.e. backports from 4.19.319 -> 4.14.419 (instead of 4.14.351)

**Comment by einargednochsson** [comment]
Most weird idea i have seen...

**Comment by harshimogalapalli** [comment]
> Could next version naming be 4.19.xxx+100
> i.e. backports from 4.19.319 -> 4.14.419 (instead of 4.14.351)

Generally the tags are typically continuous, this approach may not be practical/feasible.

I think the suggestion comes from identifying the 4.19.y tag easily ?

Note that we might have an extra tag if someone sends a bunch of backports other than what is being taken from 4.19.y. Eg: Sasha sent 189 patches to 4.14.y so we had [4.14.344-openela](https://github.com/openela/kernel-lts/commit/7a22fc46cc7a72d72b6dfdcbbc46e18c9f2caab0)
